# Generated by Django 3.2.4 on 2021-07-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('venue_type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('address_line_1', models.CharField(
                    blank=True, max_length=80)),
                ('address_line_2', models.CharField(
                    blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('county', models.CharField(
                    blank=True, max_length=80)),
                ('postcode', models.CharField(
                    blank=True, max_length=20)),
                ('email', models.EmailField(
                    blank=True, max_length=254)),
                ('phone_number', models.CharField(
                    blank=True, max_length=20)),
                ('venue_url', models.URLField(
                    blank=True, max_length=1024)),
                ('image', models.ImageField(
                    blank=True, null=True, upload_to='')),
            ],
        ),
    ]
