# Generated by Django 3.2.4 on 2022-10-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_auto_20210706_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(max_length=20),
        ),
    ]
