# Generated by Django 3.2.4 on 2021-06-07 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210607_1436'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
