# Generated by Django 3.2.4 on 2021-06-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='supplier_link',
            new_name='supplier_url',
        ),
    ]
