# Generated by Django 3.2.4 on 2021-07-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_rename_supplier_link_gift_supplier_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='group_id',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
