# Generated by Django 3.2.4 on 2021-06-26 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0010_alter_guest_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_number', models.CharField(editable=False, max_length=8)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gift_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.guest')),
            ],
        ),
    ]
