# Generated by Django 3.2.4 on 2021-06-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0010_alter_guest_message'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donation',
            new_name='Checkout',
        ),
    ]
