# Generated by Django 3.2.4 on 2021-07-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_checkout_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
