# Generated by Django 3.2.4 on 2021-06-10 08:28

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_rename_guests_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='country_code',
        ),
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='country',
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True),
        ),
    ]
