# Generated by Django 3.2.4 on 2021-06-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_guest_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='guest_id',
        ),
        migrations.AlterField(
            model_name='guest',
            name='accepted',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
