# Generated by Django 3.2.4 on 2021-06-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_auto_20210614_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='postcode',
            field=models.CharField(max_length=20),
        ),
    ]
