# Generated by Django 3.2.4 on 2021-06-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_auto_20210614_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='message',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
