# Generated by Django 3.2.4 on 2021-06-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0007_guest_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='accepted',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
