# Generated by Django 3.2.4 on 2021-06-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0008_alter_guest_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='accepted',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
