# Generated by Django 3.2.4 on 2021-07-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_menu_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='course',
            field=models.CharField(max_length=20),
        ),
    ]
