# Generated by Django 3.2.4 on 2021-07-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_alter_menu_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='menu_item',
        ),
    ]
