# Generated by Django 3.2.4 on 2021-07-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_rename_name_menu_menu_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_item',
            field=models.CharField(max_length=250),
        ),
    ]
