# Generated by Django 3.2.4 on 2021-07-19 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_auto_20210713_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-course']},
        ),
    ]
