# Generated by Django 3.2.4 on 2021-07-07 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='activity',
            new_name='event',
        ),
    ]
